"""Generate throwaway testnet wallets and write them to .env.

Four keypairs: EVM payer, EVM receiver, SVM payer, SVM receiver. Receivers' addresses become the
API's pay_to; payers' keys drive the client + funding. All testnet, zero real value. Refuses to
overwrite an existing .env (which may hold funded wallets) unless --force is passed.

    uv run python scripts/gen_wallets.py [--force]
"""

from __future__ import annotations

import sys
from pathlib import Path

import base58
from eth_account import Account
from solders.keypair import Keypair


def _svm_secret_b58(kp: Keypair) -> str:
    """Base58 of the 64-byte secret key, the format KeypairSigner.from_base58 expects."""
    return base58.b58encode(bytes(kp)).decode()

ENV_PATH = Path(__file__).resolve().parent.parent / ".env"


def main() -> None:
    if ENV_PATH.exists() and "--force" not in sys.argv:
        print(f"{ENV_PATH} already exists. Pass --force to regenerate (loses funded wallets).")
        sys.exit(1)

    evm_payer = Account.create()
    evm_receiver = Account.create()
    svm_payer = Keypair()
    svm_receiver = Keypair()

    lines = [
        "# Generated by scripts/gen_wallets.py. Testnet only. Never commit.",
        "",
        "# Receiving wallets (the API's pay_to addresses)",
        f"EVM_PAY_TO={evm_receiver.address}",
        f"SVM_PAY_TO={svm_receiver.pubkey()}",
        "",
        "# Payer wallet secrets (client side)",
        f"EVM_PAYER_KEY=0x{evm_payer.key.hex()}",
        f"SVM_PAYER_KEY={_svm_secret_b58(svm_payer)}",
        "",
        "# Receiver secrets (kept for completeness; Solana receiver ATA is created from its pubkey)",
        f"EVM_RECEIVER_KEY=0x{evm_receiver.key.hex()}",
        f"SVM_RECEIVER_KEY={_svm_secret_b58(svm_receiver)}",
        "",
        "# Convenience: payer/receiver addresses for funding scripts",
        f"EVM_PAYER_ADDRESS={evm_payer.address}",
        f"SVM_PAYER_ADDRESS={svm_payer.pubkey()}",
        f"SVM_RECEIVER_ADDRESS={svm_receiver.pubkey()}",
        "",
    ]
    ENV_PATH.write_text("\n".join(lines))
    print(f"Wrote {ENV_PATH}")
    print(f"  EVM payer    {evm_payer.address}  (fund with testnet USDC)")
    print(f"  EVM pay_to   {evm_receiver.address}")
    print(f"  SVM payer    {svm_payer.pubkey()}  (fund with devnet USDC)")
    print(f"  SVM pay_to   {svm_receiver.pubkey()}  (create its USDC ATA before settling)")


if __name__ == "__main__":
    main()
